Added check to only allow util scripts when on master branch

diff --git a/util/deploy-pypitest b/util/deploy-pypitest
--- a/util/deploy-pypitest
+++ b/util/deploy-pypitest
@@ -21,6 +21,13 @@ if [ $? -ne 0 ]; then
 	exit 3
 fi
 
+# git on master branch
+_=$(git status | grep "On branch master")
+if [ $? -ne 0 ]; then
+	echo "# ERROR: can only deploy from master branch"
+	exit 4
+fi
+
 # Register
 echo "python setup.py register -r pypitest"
 
diff --git a/util/set-version b/util/set-version
--- a/util/set-version
+++ b/util/set-version
@@ -38,6 +38,13 @@ if [ $? -ne 0 ]; then
 	exit 3
 fi
 
+# git on master branch
+_=$(git status | grep "On branch master")
+if [ $? -ne 0 ]; then
+	echo "# ERROR: can only update version from master branch"
+	exit 4
+fi
+
 # update Source code version
 if [ $SRC_VER == $VERSION ]; then
 	echo "# Source-code version correct, skipping"
